apiVersion: v1
kind: Service
metadata:
  name: pwn200
spec:
  ports:
   - port: 2007
     targetPort: 2007
  selector:
    app: pwn200
  type: LoadBalancer
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: pwn200
spec:
  podSelector:
    matchLabels:
      app: pwn200
  ingress:
  - ports:
    - port: 2007
    from: []
