apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: quickstart
spec:
  replicas: 1
  template:
    metadata:
      name: quickstart
      labels:
        app: quickstart
    spec:
      containers:
        - name: quickstart
          image: bsidespdx/quickstart
          imagePullPolicy: Always
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
