apiVersion: v1
kind: Service
metadata:
  name: quickstart
spec:
  ports:
   - port: 80
     targetPort: 80
  selector:
    app: quickstart
  type: LoadBalancer
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: quickstart
spec:
  podSelector:
    matchLabels:
      name: quickstart
  ingress:
  - ports:
    - port: 80
    from: []
