apiVersion: v1
kind: Service
metadata:
  name: pwn400
spec:
  ports:
   - port: 2048
     targetPort: 2048
  selector:
    app: pwn400
  type: LoadBalancer
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: pwn400
spec:
  podSelector:
    matchLabels:
      app: pwn400
  ingress:
  - ports:
    - port: 2048
    from: []
