apiVersion: v1
kind: Service
metadata:
  name: shellcode300
spec:
  ports:
   - port: 41414
     targetPort: 41414
  selector:
    app: shellcode300
  type: LoadBalancer
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: shellcode300
spec:
  podSelector:
    matchLabels:
      app: shellcode300
  ingress:
  - ports:
    - port: 41414
    from: []
