apiVersion: v1
kind: Service
metadata:
  name: shellcode200
spec:
  ports:
   - port: 35264
     targetPort: 35264
  selector:
    app: shellcode200
  type: LoadBalancer
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: shellcode200
spec:
  podSelector:
    matchLabels:
      app: shellcode200
  ingress:
  - ports:
    - port: 35264
    from: []
