apiVersion: v1
kind: Service
metadata:
  name: web400
spec:
  ports:
   - port: 80
     targetPort: 5001
  selector:
    app: web400
  type: LoadBalancer
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: web400
spec:
  podSelector:
    matchLabels:
      app: web400
  ingress:
  - ports:
    - port: 5001
    from: []
