apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: leek
spec:
  replicas: 1
  template:
    metadata:
      name: leek
      labels:
        app: leek
    spec:
      containers:
        - name: leek
          image: gcr.io/testing-bsidespdx-ctf-2017/leek
          imagePullPolicy: Always
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
