apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shellcode200
spec:
  replicas: 1
  template:
    metadata:
      name: shellcode200
      labels:
        app: shellcode200
    spec:
      containers:
        - name: shellcode200
          image: gcr.io/%PROJECT_ID%/shellcode200
          imagePullPolicy: Always
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
       
