apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nodes
spec:
  replicas: 1
  template:
    metadata:
      name: nodes
      labels:
        app: nodes
    spec:
      containers:
        - name: leek
          image: gcr.io/testing-bsidespdx-ctf-2017/nodes
          imagePullPolicy: Always
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
